repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.21.2
  hooks:
    - id: commitizen
      stages: [commit-msg]
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.2.0
  hooks:
    - id: detect-secrets
      args:
        - '--baseline'
        - .secrets.baseline
      exclude: terraform.tfstate
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
    - id: terraform_tfsec
      files: (\.tf|\.tfvars)$
      args:
        - '--args=--exclude-downloaded-modules'
- repo: https://github.com/bridgecrewio/checkov.git
  rev: 2.0.929
  hooks:
  - id: checkov
